### PR TITLE
Fix compile warnings

### LINKED ISSUE #94: ci: Build with `-Werror=compat -Werror=default`
We should build with these conservative warning sets enabled and turned into errors in CI so that we don't end up accidentally introducing them, and so that we make sure to fix new warnings added by new versions of GHC.

### PR DESCRIPTION
**Pull request by langston-barrett**
Fixes #94.

### CODE REVIEW

File: semmc-arm/src/SemMC/Architecture/A32.hs [hunk 1]
```diff
@@ -13,7 +13,10 @@
 {-# LANGUAGE TypeOperators #-}
 {-# LANGUAGE UndecidableInstances #-}
 {-# LANGUAGE ViewPatterns #-}
+
 {-# OPTIONS_GHC -Wno-orphans #-}
+{-# OPTIONS_GHC -Wno-type-defaults #-}
```
Comment (RyanGlScott) [inline semmc-arm/src/SemMC/Architecture/A32.hs]: A bit unfortunate to have to have to disable this warning wholesale, in my opinion. Couldn't we just monomorphize the expressions that trigger this warning?

(A similar question applies to the use of `-Wno-type-defaults` in `semmc-arm/src/SemMC/Architecture/AArch32.hs`.)

File: semmc-arm/src/SemMC/Architecture/AArch32.hs [hunk 2]
```diff
@@ -25,6 +25,10 @@
 {-# LANGUAGE UndecidableInstances #-}
 
 {-# OPTIONS_GHC -Wno-orphans #-}
+{-# OPTIONS_GHC -Wno-type-defaults #-}
+
+-- TODO(#95): Initialize `exprInterp` field of `FunctionInterpretation`
+{-# OPTIONS_GHC -Wno-missing-fields #-}
```
Comment (RyanGlScott) [inline semmc-arm/src/SemMC/Architecture/AArch32.hs]: How would you feel about filling in each `FunctionInterpretation` value with `exprInterp = error "..."` so that we don't have to disable this warning wholesale? Feel free to say "no" if you think this is too much work :)

File: semmc/tests/semstore/TestArchPropGen.hs [hunk 3]
```diff
@@ -13,6 +13,8 @@
 {-# LANGUAGE TypeFamilies #-}
 {-# LANGUAGE TypeOperators #-}
 
+{-# OPTIONS_GHC -Wno-incomplete-patterns#-}
```
Comment (RyanGlScott) [inline semmc/tests/semstore/TestArchPropGen.hs]: Please don't disable _this_ warning, if nothing. I'd much prefer filling out the remaining cases with `error` calls rather than disabling `-Wincomplete-patterns` entirely.

**Review by RyanGlScott — COMMENTED** [review]
I'm somewhat surprised that you didn't have to fix https://github.com/GaloisInc/semmc/issues/70 in the course of making all the code `-Wall`-clean. Are you sure that CI is actually building everything? (I'm a bit worried that some code containing warnings might have been skipped over due to caching.)

**Comment by langston-barrett** [comment]
That surprises me too. I did fix #70, so hopefully that code (and hence, everything) will be rebuilt now.

**Comment by langston-barrett** [comment]
I'm also doing `cabal clean && cabal build all` locally just to be sure.

**Review by RyanGlScott — APPROVED** [review]

**Comment by RyanGlScott** [comment]
Also make sure to say "fixes #70" somewhere in the commit message as well :)
